const express = require('express');
const cors = require('cors');
const app = express();

// Enable CORS
app.use(cors());
app.use(express.json());

const dares = [
    "Take a picture with your favorite book!",
    "Show off your best dance move!",
    "Take a picture while doing a handstand (or trying to)!",
    "Sing a song out loud and capture the moment!",
    "Wear your wildest outfit and take a photo!",
    "Take a picture with something yellow!",
    "Strike a superhero pose!",
    "Find something red and snap a photo with it!",
    "Take a picture of yourself upside down!",
    "Mimic your favorite movie scene and capture it!",
    "Take a selfie with your pet (or pretend if you don't have one)!",
    "Draw a smiley face and take a picture with it!",
    "Take a photo with something that starts with the letter 'P'!",
    "Show your best impression of a famous celebrity!",
    "Pretend to be asleep and take a selfie!",
    "Take a photo next to the messiest part of your room!",
    "Balance something on your head and take a picture!",
    "Find the nearest plant and take a selfie with it!",
    "Take a photo doing a silly dance!",
    "Show off your favorite pair of shoes in a photo!",
    "Take a picture pretending to be a statue!",
    "Take a selfie with something that makes you smile!",
    "Wear sunglasses indoors and take a picture!",
    "Take a photo with the sky behind you!",
    "Show us your best silly face in a photo!",
    "Take a picture with something that smells nice!",
    "Make the peace sign and snap a selfie!",
    "Take a picture in your favorite cozy spot!",
    "Pose like you're running away from something!",
    "Take a picture with your favorite snack!",
    "Show us your best funny hat or create one!",
    "Take a picture standing on one leg!",
    "Pretend to be a superhero flying and take a photo!",
    "Find something tiny and take a picture with it!",
    "Take a photo with something that makes you happy!",
    "Take a picture with your hands covering your face!",
    "Create a heart shape with your hands and take a selfie!",
    "Take a picture with something shiny!",
    "Find a mirror and take a creative mirror selfie!",
    "Take a photo of yourself holding your favorite drink!",
    "Snap a picture while jumping in the air!",
    "Find a family member or friend and take a funny selfie together!",
    "Take a picture with something soft and cuddly!",
    "Pretend to be a famous athlete and capture the moment!",
    "Take a picture with something blue!",
    "Strike your best yoga pose and take a picture!",
    "Take a picture showing your favorite piece of jewelry!",
    "Take a photo pretending to hold the moon or sun!",
    "Show us your best thumbs-up in a picture!",
    "Take a picture with something that starts with the letter 'S'!",
    "Snap a photo showing your silliest face ever!",
    "Take a picture wearing something on your head that isn't a hat!",
    "Find something colorful and take a selfie with it!",
    "Take a picture with something that makes you laugh!",
    "Strike your best superhero landing pose in a picture!",
    "Find something in nature and take a photo with it!",
    "Take a picture showing your proudest smile!",
    "Snap a picture with your favorite accessory!",
    "Take a picture holding an object in a weird way!",
    "Find a fruit and take a creative picture with it!",
    "Take a selfie while lying down!",
    "Pretend you're a famous chef and take a cooking-themed photo!",
    "Take a photo making a funny hand gesture!",
    "Find something round and take a picture with it!",
    "Strike your best model pose in a photo!",
    "Take a picture with something that's taller than you!",
    "Take a photo showing off your artistic skills!",
    "Take a picture while making the biggest smile you can!",
    "Snap a picture while holding something from your childhood!",
    "Take a picture pretending to fly like an airplane!",
    "Take a selfie with the oldest thing you can find!",
    "Show us your best balancing act in a picture!",
    "Take a photo of yourself looking super mysterious!",
    "Pretend you're at a red carpet event and take a picture!",
    "Take a picture showing off your muscles!",
    "Take a photo of yourself reading something interesting!",
    "Strike a pose like you're in a music video and take a picture!",
    "Take a picture with something you can't live without!",
    "Find something that represents peace and take a picture with it!",
    "Take a picture of yourself pretending to be in a storm!",
    "Pretend you're on vacation and snap a selfie!",
    "Take a photo with something that starts with the letter 'C'!",
    "Pretend you're a famous artist and take a picture with your 'art'!",
    "Take a picture of yourself making a silly face with a spoon!",
    "Snap a picture holding something unusual!",
    "Take a photo of yourself in a disguise!",
    "Take a picture with something that starts with the letter 'T'!",
    "Show off your best thumbs-down in a photo!",
    "Pretend to be a detective and take a mysterious photo!",
    "Take a picture with the most colorful thing you own!",
    "Take a picture pretending you're in outer space!",
    "Find something cold and take a picture with it!",
    "Take a photo while showing your favorite hand gesture!",
    "Pretend you're a famous dancer and take a dance-themed picture!",
    "Take a picture of yourself pretending to be a superhero flying away!",
    "Find something soft and take a cozy selfie with it!",
    "Pretend you're a famous explorer and take an adventurous photo!",
    "Take a photo of yourself pretending to be a rockstar!",
    "Find something that smells good and take a photo with it!",
    "Pretend you're at a beach and take a sunny selfie!",
    "Take a photo pretending to be in a spy movie!",
    "Find something old-fashioned and take a picture with it!",
    "Pretend you're a famous athlete and snap a sports-themed selfie!",
    "Take a picture with something that sparkles!",
    "Pretend to be a famous movie star and take a glamorous selfie!",
    "Snap a picture while standing on one foot!",
    "Pretend to be a statue and take a picture holding very still!",
    "Take a picture with something you love to eat!",
    "Pretend you're a famous scientist and take a lab-themed photo!",
    "Find something heart-shaped and take a picture with it!",
    "Take a picture of yourself doing your best silly dance!",
    "Pretend to be a pirate and snap a picture with your 'treasure'!",
    "Take a picture with the oldest thing in your room!",
    "Pretend you're a fashion model and take a runway-style photo!",
    "Snap a picture with something that starts with the letter 'B'!",
    "Pretend you're an astronaut and take a space-themed selfie!",
    "Take a picture showing off your best victory pose!",
    "Snap a picture of yourself with something super shiny!",
    "Take a photo with something that brings you joy!",
    "Pretend you're on a game show and snap a victory selfie!",
    "Take a photo of yourself pretending to juggle something!",
    "Pretend you're a famous actor and take a dramatic selfie!",
    "Take a picture with something that's extremely colorful!",
    "Pretend you're a famous photographer and take a creative selfie!",
    "Take a photo of yourself pretending to run a marathon!",
    "Pretend you're a famous detective and take a mystery-themed selfie!",
    "Snap a picture of yourself making the funniest face possible!",
    "Take a photo with something that starts with the letter 'F'!",
    "Take a picture of yourself jumping in the air!",
    "Snap a picture with something that makes a loud noise!",
    "Take a photo pretending to be on a cooking show!",
    "Take a picture with something that represents happiness!",
    "Snap a photo pretending you're about to take flight!",
    "Pretend you're a famous magician and take a magical-themed selfie!",
    "Take a photo with something that smells amazing!",
    "Pretend you're in a music band and snap a rockstar selfie!",
    "Take a picture with something that starts with the letter 'M'!",
    "Snap a picture showing off your favorite hobby!",
    "Take a picture of yourself making a goofy expression!",
    "Pretend you're a famous adventurer and take an exploration-themed photo!",
    "Snap a picture with something that makes you laugh!",
    "Take a photo of yourself pretending to be a famous painter!",
    "Pretend you're a famous chef and snap a cooking selfie!",
    "Take a picture with something that starts with the letter 'N'!",
    "Snap a picture of yourself pretending to hold the sun!",
    "Take a picture with something that makes you feel warm and cozy!",
    "Pretend you're a famous athlete and take a sports-themed selfie!",
    "Take a photo with something that starts with the letter 'R'!",
    "Pretend you're a famous scientist and take a picture in 'the lab'!",
    "Take a photo of yourself showing your best dance move!",
    "Snap a picture with something that represents peace and tranquility!",
    "Take a picture pretending to be a famous explorer!",
    "Take a photo with something from your favorite movie!",
    "Pretend you're a rockstar and snap a concert-style selfie!",
    "Take a picture with something that starts with the letter 'V'!",
    "Pretend you're a famous artist and take a picture with your 'masterpiece'!",
    "Snap a picture with something that brings back childhood memories!",
    "Take a picture with your best victory pose!",
    "Pretend you're a famous athlete and snap a picture while 'winning'!",
    "Take a photo with something that makes you laugh!",
    "Pretend you're an explorer and take a selfie with a 'discovery'!",
    "Take a picture of yourself jumping in the air!",
    "Pretend you're a superhero and snap a flying pose selfie!",
    "Take a photo with something shiny!",
    "Pretend you're a famous singer and take a music-themed selfie!",
    "Snap a picture with something that smells good!",
    "Pretend you're a famous scientist and take a lab-themed selfie!",
    "Take a picture showing your best funny face!",
    "Pretend you're a fashion model and snap a runway selfie!",
    "Snap a picture of yourself pretending to fly a plane!",
    "Take a photo with something colorful!",
    "Pretend you're on a game show and snap a victory selfie!",
    "Take a picture of yourself holding something tiny!",
    "Pretend you're a rockstar and snap a picture of your 'concert'!",
    "Take a photo with something that makes you happy!",
    "Pretend you're a famous detective and take a mystery-themed selfie!",
    "Snap a picture of yourself making the biggest smile possible!",
    "Take a picture with something that represents peace!",
    "Pretend you're an astronaut and snap a space-themed selfie!",
    "Snap a picture with something you love to eat!",
    "Take a photo of yourself jumping in the air!",
    "Pretend you're a famous chef and take a cooking-themed selfie!",
    "Take a picture with something that starts with the letter 'G'!",
    "Snap a picture pretending you're about to win a race!",
    "Pretend you're a famous singer and take a music-themed selfie!",
    "Take a photo of yourself showing off your best silly face!",
    "Snap a picture pretending to be a superhero!",
    "Take a photo with something that makes you smile!",
    "Pretend you're a famous artist and snap a picture with your 'art'!",
    "Take a picture of yourself holding something unusual!",
    "Snap a picture of yourself pretending to be a famous explorer!",
    "Take a photo showing your best funny face!",
    "Pretend you're a detective and snap a mystery-themed selfie!",
    "Take a picture with something you love!",
    "Snap a picture of yourself jumping in the air!",
    "Pretend you're a rockstar and take a concert-style selfie!",
    "Take a picture with something that represents happiness!",
    "Snap a picture with your favorite accessory!",
    "Take a photo of yourself pretending to hold the sun or moon!",
    "Pretend you're an astronaut and snap a space-themed selfie!",
    "Snap a picture of yourself making a silly face!",
    "Take a picture with something colorful!",
    "Pretend you're a famous chef and take a cooking-themed selfie!",
    "Take a photo with something that makes you smile!",
    "Snap a picture with something tiny!",
    "Take a picture of yourself holding something from your childhood!",
    "Pretend you're a famous detective and take a mystery-themed selfie!"
  ];
  

// Route to get the daily dare
app.get('/daily-dare', (req, res) => {
    const startOfYear = new Date(new Date().getFullYear(), 0, 1);
    const dayOfYear = Math.floor((new Date() - startOfYear) / (1000 * 60 * 60 * 24));
    const dare = dares[dayOfYear % dares.length]; // Rotate dares
    res.json({ dare });
});

// Start the server
const port = process.env.PORT || 3001;
app.listen(port, () => {
  console.log(`Server running on port ${port}`);
});
